# Generated by Django 5.2.8 on 2026-03-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
