# Generated by Django 5.2.8 on 2026-04-30 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_progress_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Message subject line', max_length=200)),
                ('sender_name', models.CharField(help_text="Name of sender (e.g., 'Dr Bérengère Digard' or 'The Eye's Mind research team')", max_length=200)),
                ('body', models.TextField(help_text='Message content. Supports basic HTML: <p>, <strong>, <em>, <a>, <h4>, <ul>, <li>')),
                ('is_published', models.BooleanField(default=False, help_text='Only published messages are visible to participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
