# Generated by Django 5.2.8 on 2026-04-30 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Researcher',
        ),
    ]
