# Generated by Django 5.2.8 on 2026-08-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_unused_participant_researcher_models'),
        ('surveys', '0029_alter_questiongroup_result_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unlocks_with_survey',
            field=models.ForeignKey(blank=True, help_text="Optional: only show this message once the participant has completed as many surveys as this feedback survey's 'Show after N surveys' setting. Leave blank to show the message to everyone as soon as it's published.", limit_choices_to={'is_feedback': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlock_messages', to='surveys.survey'),
        ),
    ]
