# Generated by Django 5.2.8 on 2026-09-29 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message_unlocks_with_survey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datadownloadlog',
            name='researcher_email',
            field=models.EmailField(blank=True, help_text="Snapshot of the researcher's email at the time of download, preserved even if the account is later deleted.", max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='created_by_email',
            field=models.EmailField(blank=True, help_text="Snapshot of the sender's email at the time this message was created, preserved even if the account is later deleted.", max_length=254),
        ),
        migrations.AlterField(
            model_name='datadownloadlog',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(help_text='Message content, written in Markdown (same as survey descriptions/instructions and the consent form) — e.g. **bold**, *italic*, [link](url), # headings, - list items. Rendered as HTML for participants, not shown as raw Markdown.'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
