# Generated by Django 5.2.8 on 2025-11-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_text',
            field=models.TextField(blank=True, help_text='The consent form text that was presented to the user during registration'),
        ),
    ]
