# Generated by Django 5.2.8 on 2025-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_consent_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Research Participation Consent Form', help_text='Title of the consent form', max_length=200)),
                ('content', models.TextField(help_text='Full text of the consent form shown to participants during registration')),
                ('is_active', models.BooleanField(default=True, help_text='Only one consent form should be active at a time')),
                ('version', models.CharField(blank=True, help_text="Version identifier for this consent form (e.g., 'v1.0', '2024-01')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consent Form',
                'verbose_name_plural': 'Consent Forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
