# Generated by Django 5.2.8 on 2025-11-17 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_consentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the person being invited', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique invitation token', unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this invitation expires')),
                ('used', models.BooleanField(default=False, help_text='Whether this invitation has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this invitation was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(help_text='The researcher who sent this invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Researcher Invitation',
                'verbose_name_plural': 'Researcher Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
