# Generated by Django 5.2.8 on 2026-08-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_researcherinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown-formatted text explaining the withdrawal process and consequences.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one withdrawal text should be active at a time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Text',
                'verbose_name_plural': 'Withdrawal Texts',
            },
        ),
    ]
