# Generated by Django 5.2.8 on 2026-08-19 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_researcherinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(help_text='Anonymised participant ID at time of withdrawal (e.g. PRH-2026-0042)', max_length=50)),
                ('withdrawn_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_survey_title', models.CharField(blank=True, help_text='Title of the exit survey completed, if any', max_length=200)),
                ('responses', models.JSONField(default=list, help_text='List of {question, answer} dicts from the exit survey')),
            ],
            options={
                'verbose_name': 'Withdrawal Record',
                'verbose_name_plural': 'Withdrawal Records',
                'ordering': ['-withdrawn_at'],
            },
        ),
    ]
