# Generated by Django 5.2.8 on 2025-11-11 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_file', models.FileField(help_text='Upload lab.js task HTML file or archive', upload_to='lab_tasks/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Optional time limit for task completion', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions shown to participants before starting the task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tasks', to='core.domain')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Task',
                'verbose_name_plural': 'Lab Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('results_data', models.JSONField(blank=True, help_text='JSON data from lab.js task results', null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, help_text='Total time spent on the task in seconds', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.labtask')),
            ],
            options={
                'verbose_name': 'Task Submission',
                'verbose_name_plural': 'Task Submissions',
                'ordering': ['-started_at'],
                'unique_together': {('task', 'participant')},
            },
        ),
    ]
