# Generated by Django 5.2.8 on 2025-11-24 15:44

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtask',
            name='task_file',
        ),
        migrations.AddField(
            model_name='labtask',
            name='task_directory',
            field=models.CharField(blank=True, help_text='Path to unpacked task directory', max_length=500),
        ),
        migrations.AddField(
            model_name='labtask',
            name='task_slug',
            field=models.SlugField(blank=True, help_text='URL-safe identifier, generated from title', max_length=250),
        ),
        migrations.AddField(
            model_name='labtask',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Upload lab.js task as a .zip file (must contain index.html)', null=True, upload_to='lab_tasks/zips/', validators=[tasks.models.validate_zip_file]),
        ),
    ]
