# Generated by Django 5.2.8 on 2026-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_labtask_task_file_labtask_task_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='trial_sender_filter',
            field=models.CharField(blank=True, help_text="Optional: comma-separated list of sender names to filter trial data to (e.g. 'Trial' or 'Trial, Stimulus'). If blank, all rows where ended_on='response' are included.", max_length=500),
        ),
    ]
