# Generated by Django 5.2.8 on 2026-02-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_labtask_trial_sender_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='is_test',
            field=models.BooleanField(default=False, help_text='True if submitted by a researcher or staff member for testing purposes. Safe to delete after review.'),
        ),
    ]
