# Generated by Django 5.2.8 on 2026-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasksubmission_is_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtask',
            options={'ordering': ['-is_priority', '-created_at'], 'verbose_name': 'Lab Task', 'verbose_name_plural': 'Lab Tasks'},
        ),
        migrations.AddField(
            model_name='labtask',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Mark this task as a priority. Priority tasks appear at the top of the list.'),
        ),
    ]
