# Generated by Django 5.2.8 on 2026-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_labtask_options_labtask_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='min_window_height',
            field=models.PositiveIntegerField(default=768, help_text="Minimum browser window height in pixels (only enforced if 'requires min window size' is checked)."),
        ),
        migrations.AddField(
            model_name='labtask',
            name='min_window_width',
            field=models.PositiveIntegerField(default=1024, help_text="Minimum browser window width in pixels (only enforced if 'requires min window size' is checked)."),
        ),
        migrations.AddField(
            model_name='labtask',
            name='requires_min_window_size',
            field=models.BooleanField(default=False, help_text='Require the browser window to be at least the minimum size below before participants can start (e.g. for visual tasks that need enough screen space for usable data).'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='window_height',
            field=models.PositiveIntegerField(blank=True, help_text='Browser window height (px) recorded when the participant started the task.', null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='window_width',
            field=models.PositiveIntegerField(blank=True, help_text='Browser window width (px) recorded when the participant started the task. Logged regardless of whether a minimum size was enforced, as a data-quality fallback.', null=True),
        ),
    ]
