# Generated by Django 5.2.8 on 2025-11-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_unique_order_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order for each participant (using participant ID as seed for consistency)'),
        ),
    ]
