# Generated by Django 5.2.8 on 2025-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_add_randomize_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reverse_coded',
            field=models.BooleanField(default=False, help_text='Reverse code this question (invert scale values before storing). Useful for detecting response patterns.'),
        ),
    ]
