# Generated by Django 5.2.8 on 2026-02-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_add_reverse_coded'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikertScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this scale, e.g. 'Agreement 1-5' or 'Vividness 0-10'", max_length=200)),
                ('min_value', models.IntegerField(default=1)),
                ('max_value', models.IntegerField(default=5)),
                ('scale_labels', models.JSONField(blank=True, default=dict, help_text='Labels for each scale value. Example: {"1": "Never", "2": "Rarely", "3": "Sometimes", "4": "Often", "5": "Always"}')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likert_scales', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Likert Scale',
                'verbose_name_plural': 'Likert Scales',
                'ordering': ['survey', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='likert_scale',
            field=models.ForeignKey(blank=True, help_text='Select a Likert scale for this question. Leave blank to use the survey default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='surveys.likertscale'),
        ),
    ]
