# Generated by Django 5.2.8 on 2026-02-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_likertscale_question_likert_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False, help_text='(Multiple choice only) Allow multiple selections. If False, participants can select only one option.'),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='(Multiple choice only) Options for multiple choice questions. Format: {"1": "Option A", "2": "Option B", "3": "Option C"}'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('likert', 'Likert Scale'), ('multiple_choice', 'Multiple Choice'), ('free_text', 'Free Text')], default='likert', help_text='Type of question', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='likert_scale',
            field=models.ForeignKey(blank=True, help_text='(Likert only) Select a Likert scale for this question. Leave blank to use the survey default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='surveys.likertscale'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reverse_coded',
            field=models.BooleanField(default=False, help_text='(Likert only) Reverse code this question (invert scale values before storing). Useful for detecting response patterns.'),
        ),
    ]
