# Generated by Django 5.2.8 on 2026-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_question_allow_multiple_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='allow_multiple',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('likert', 'Likert Scale'), ('multiple_choice_single', 'Multiple Choice (Select One)'), ('multiple_choice_multi', 'Multiple Choice (Select Multiple)'), ('free_text', 'Free Text')], default='likert', help_text='Type of question', max_length=30),
        ),
    ]
