# Generated by Django 5.2.8 on 2026-02-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_remove_question_allow_multiple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(blank=True, help_text="Question number within the group (e.g., '01', '02'). Leave blank for ungrouped questions.", max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(help_text="Short code for this group (e.g., '1', '2', 'demographics'). Used in question identifiers like '1_01', '1_02'.", max_length=50)),
                ('title', models.CharField(help_text="The group heading/statement (e.g., 'Think of a relative or friend')", max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional additional instructions for this group of questions')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this group. Set to 0 for automatic ordering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Question Group',
                'verbose_name_plural': 'Question Groups',
                'ordering': ['survey', 'order', 'id'],
                'unique_together': {('survey', 'group_code')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Optional: Assign this question to a group. Questions in groups get identifiers like '1_01', '1_02', etc.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='surveys.questiongroup'),
        ),
    ]
