# Generated by Django 5.2.8 on 2026-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_question_question_number_questiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, db_index=True, help_text="Composite identifier stored in database (e.g., 'A_01', 'B_02', 'Q5'). Auto-generated from group_code and question_number.", max_length=50),
        ),
    ]
