# Generated by Django 5.2.8 on 2026-02-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_question_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantresponse',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Marks this as test data submitted by researchers/staff'),
        ),
    ]
