# Generated by Django 5.2.8 on 2026-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_participantresponse_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_trigger_question',
            field=models.BooleanField(default=False, help_text='Check this if this question controls the visibility of follow-up questions in the same group (e.g., a yes/no question)'),
        ),
        migrations.AddField(
            model_name='question',
            name='trigger_value',
            field=models.CharField(blank=True, help_text='The answer value that enables follow-up questions (e.g., "2" for Yes on a 1-2 scale). Leave blank if not a trigger question.', max_length=50),
        ),
    ]
