# Generated by Django 5.2.8 on 2026-02-24 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_add_trigger_question_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='is_question',
            field=models.BooleanField(default=False, help_text='Check this if this group header is itself a question that must be answered (e.g., a yes/no question)'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='likert_scale',
            field=models.ForeignKey(blank=True, help_text='(If is_question) The Likert scale for this question. Leave blank to use survey default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_groups', to='surveys.likertscale'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='trigger_value',
            field=models.CharField(blank=True, help_text='(If is_question) The answer value that shows the questions in this group (e.g., "2" for Yes). Leave blank to always show questions.', max_length=50),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(help_text="The group heading/statement. If this is a question, this is the question text (e.g., 'Think of a relative or friend?')", max_length=500),
        ),
        migrations.CreateModel(
            name='ParticipantGroupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_test', models.BooleanField(default=False, help_text='Marks this as test data submitted by researchers/staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_responses', to=settings.AUTH_USER_MODEL)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.questiongroup')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_responses', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Group Response',
                'verbose_name_plural': 'Group Responses',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'question_group', 'participant')},
            },
        ),
    ]
