# Generated by Django 5.2.8 on 2026-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_add_group_question_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='is_question',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='likert_scale',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='trigger_value',
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='title',
            field=models.CharField(help_text="The group heading/statement (e.g., 'Think of a relative or friend')", max_length=500),
        ),
        migrations.DeleteModel(
            name='ParticipantGroupResponse',
        ),
    ]
