# Generated by Django 5.2.8 on 2026-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_revert_group_question_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_trigger_question',
        ),
        migrations.AddField(
            model_name='question',
            name='controls_next_n_questions',
            field=models.PositiveIntegerField(default=0, help_text='Number of following questions controlled by this question. Set to 0 if not a trigger. Example: Set to 3 to control the next 3 questions.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='trigger_value',
            field=models.CharField(blank=True, help_text='The answer value that enables controlled questions (e.g., "2" for Yes on a 1-2 scale). Leave blank if controls_next_n_questions is 0.', max_length=50),
        ),
    ]
