# Generated by Django 5.2.8 on 2026-02-25 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_replace_with_n_questions_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scale_factor',
            field=models.IntegerField(default=1, help_text='(Likert only) Multiply the answer by this factor before storing. Applied after reverse coding. Example: factor of 2 converts 1-5 scale to 2-10.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
