# Generated by Django 5.2.8 on 2026-02-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_question_scale_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='description',
        ),
    ]
