# Generated by Django 5.2.8 on 2026-03-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_remove_questiongroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='show_title',
            field=models.BooleanField(default=True, help_text='Show the group title to participants. Uncheck to use this group as a hidden subscale for scoring/analysis only.'),
        ),
    ]
