# Generated by Django 5.2.8 on 2026-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_questiongroup_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='(Multiple choice only) Options for multiple choice questions. Format: {"1": "Option A", "2": "Option B", "3": "Option C"}. To disable an option (visible but not selectable), use an array: {"1": "Option A", "2": ["Option B (disabled)"], "3": "Option C"}'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('likert', 'Likert Scale'), ('multiple_choice_single', 'Multiple Choice (Select One)'), ('multiple_choice_multi', 'Multiple Choice (Select Multiple)'), ('free_text', 'Free Text'), ('dropdown_year', 'Dropdown (Year)'), ('dropdown_month', 'Dropdown (Month)')], default='likert', help_text='Type of question', max_length=30),
        ),
    ]
