# Generated by Django 5.2.8 on 2026-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_alter_question_options_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='Question text/label. Can be left blank for self-explanatory question types like dropdowns.'),
        ),
    ]
