# Generated by Django 5.2.8 on 2026-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('likert', 'Likert Scale'), ('multiple_choice_single', 'Multiple Choice (Select One)'), ('multiple_choice_multi', 'Multiple Choice (Select Multiple)'), ('free_text', 'Free Text'), ('dropdown_year', 'Dropdown (Year)'), ('dropdown_month', 'Dropdown (Month)'), ('dropdown_country', 'Dropdown (Country)')], default='likert', help_text='Type of question', max_length=30),
        ),
    ]
