# Generated by Django 5.2.8 on 2026-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-is_priority', '-created_at'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AddField(
            model_name='survey',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Mark this survey as a priority. Priority surveys appear at the top of the list.'),
        ),
    ]
