# Generated by Django 5.2.8 on 2026-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_add_result_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='instructions',
            field=models.TextField(blank=True, help_text='Optional survey-specific instructions shown in the sidebar before the standard how-to-answer points.'),
        ),
    ]
