# Generated by Django 5.2.8 on 2026-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_add_survey_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_feedback',
            field=models.BooleanField(default=False, help_text='Mark this as a mid-study feedback survey. Feedback surveys are hidden from the participant dashboard and managed under Core in the admin.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='show_after_n_surveys',
            field=models.PositiveIntegerField(default=2, help_text='(Feedback surveys only) Show this form on the participant account page after they have completed this many regular surveys.'),
        ),
    ]
