# Generated by Django 5.2.8 on 2026-08-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_add_feedback_survey_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitSurvey',
            fields=[
            ],
            options={
                'verbose_name': 'Exit Survey',
                'verbose_name_plural': 'Exit Surveys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('surveys.survey',),
        ),
        migrations.CreateModel(
            name='FeedbackSurvey',
            fields=[
            ],
            options={
                'verbose_name': 'Feedback Survey',
                'verbose_name_plural': 'Feedback Surveys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('surveys.survey',),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_exit_survey',
            field=models.BooleanField(default=False, help_text='Mark this as an exit survey. Exit surveys are shown to participants when they choose to withdraw from the study.'),
        ),
    ]
