# Generated by Django 5.2.8 on 2026-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_exitsurvey_feedbacksurvey_survey_is_exit_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicSurvey',
            fields=[
            ],
            options={
                'verbose_name': 'Demographic Survey',
                'verbose_name_plural': 'Demographic Survey',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('surveys.survey',),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_demographic',
            field=models.BooleanField(default=False, help_text='Mark this as the demographic gateway survey. Participants must complete it before accessing any other surveys or tasks. Only one survey should have this enabled at a time.'),
        ),
    ]
